# Generated by Django 6.0.4 on 2026-05-20 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asignaciones", "0002_alter_asignacion_semestre_delete_semestre"),
        ("cambios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="solicitudcambio",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "pendiente")),
                fields=("asignacion",),
                name="unique_pending_solicitud_per_asignacion",
            ),
        ),
    ]
