# Generated by Django 6.0.4 on 2026-05-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id_semestre', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('periodo', models.PositiveSmallIntegerField(verbose_name='Periodo')),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'db_table': 'semestre',
                'ordering': ['-anio', '-periodo'],
                'constraints': [models.UniqueConstraint(fields=('anio', 'periodo'), name='uq_semestre_anio_periodo'), models.CheckConstraint(condition=models.Q(('periodo__in', [1, 2])), name='chk_semestre_periodo_1_2')],
            },
        ),
    ]
