# Generated by Django 6.0.4 on 2026-05-07 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id_semestre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['-id_semestre'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='horarios.horario')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='asignaciones.semestre')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('horario', 'semestre'), name='uq_asig_horario_semestre'), models.UniqueConstraint(fields=('monitor', 'horario', 'semestre'), name='uq_asig_monitor_horario_semestre')],
            },
        ),
    ]
